version: '3.9'

services:

  estaciones:
    container_name: estaciones
    build: ./estaciones
    ports:
      - "8082:8082"
    expose:
      - "8082"
    volumes:
      - db-volume:/app/BD

  alquiler:
    container_name: alquiler
    build: ./alquiler
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - estaciones
    volumes:
      - db-volume:/app/BD

  gateway:
    container_name: gateway
    build: ./Gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
        - alquiler
        - estaciones

volumes:
  db-volume:
